# Generated by Django 2.2.8 on 2021-01-06 20:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=32)),
                ('Desc', models.TextField(blank=True, max_length=50)),
                ('Loc', models.CharField(max_length=32)),
                ('FromDate', models.DateField(default=datetime.date.today)),
                ('FromTime', models.TimeField(default=django.utils.timezone.now)),
                ('ToDate', models.DateField(default=datetime.date.today)),
                ('RegEndDate', models.DateField(default=datetime.date.today)),
                ('HostEmail', models.EmailField(max_length=254)),
                ('HostPassword', models.CharField(max_length=32)),
                ('Status', models.IntegerField()),
            ],
        ),
    ]
