# Generated by Django 2.2.8 on 2021-01-06 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='RegEndTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='ToTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
