# Generated by Django 2.2.8 on 2021-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0002_auto_20210107_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Event', models.CharField(max_length=32)),
                ('RegType', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=32)),
                ('Number', models.IntegerField()),
            ],
        ),
    ]
