# Generated by Django 2.2.8 on 2021-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0002_auto_20210123_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Number',
            field=models.IntegerField(default=1),
        ),
    ]
