# Generated by Django 2.2.8 on 2021-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0003_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='RegType',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Individual', max_length=32),
        ),
    ]
