# Generated by Django 2.2.8 on 2021-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0003_auto_20210124_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Status',
        ),
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Festivals', 'Festivals'), ('Competition', 'Competition'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='Poster',
            field=models.URLField(blank=True),
        ),
    ]
